# 基础镜像
FROM  openjdk:8u342-jdk

ARG TIME_ZONE=Asia/Shanghai
RUN mkdir -p /home/yt\
    && echo ${TIME_ZONE} > /etc/timezone
# 创建目录
RUN mkdir -p /home/cg
# 指定路径
WORKDIR /home/cg
# 复制jar文件到路径
COPY cg-gateway-application.jar /home/cg/gateway.jar
# 启动网关服务
ENTRYPOINT [\
    "java",\
    "-Xms256m", \
    "-Xmx256m", \
    "-Xmn128m", \
    "-jar",\
    "gateway.jar"\
    ]